In [1]:
import pandas as pd

from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import RobustScaler

In [2]:
df = pd.read_csv("Admission_Prediction.csv")

df.head()

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit,Year,University_Name,region
0,1,337,118,4,4.5,4.5,9.65,1,0.92,2022,Indian Institute of Technology Kharagpur,East
1,2,324,107,4,4.0,4.5,8.87,1,0.76,2022,National Institute of Technology Karnataka,South
2,3,316,104,3,3.0,3.5,8.00,1,0.72,2022,Gujarat University,West
3,4,322,110,3,3.5,2.5,8.67,1,0.80,2022,Jamia Millia Islamia,North
4,5,314,103,2,2.0,3.0,8.21,0,0.65,2022,Jamia Millia Islamia,North

In [11]:
# select num data to scale 
num = df.select_dtypes(include="number")
print(num.head())

   Serial No.  GRE Score  TOEFL Score  University Rating  SOP  LOR  CGPA  \
0           1        337          118                  4  4.5  4.5  9.65
1           2        324          107                  4  4.0  4.5  8.87
2           3        316          104                  3  3.0  3.5  8.00
3           4        322          110                  3  3.5  2.5  8.67
4           5        314          103                  2  2.0  3.0  8.21

   Research  Chance of Admit  Year
0         1             0.92  2022
1         1             0.76  2022
2         1             0.72  2022
3         1             0.80  2022
4         0             0.65  2022

In [17]:

#select the input feature and remove the target col
x = num.drop("Chance of Admit", axis=1)
# remove unwanted columns 
x = num.drop("Serial No.", axis=1)

In [21]:
# min max scaler 
minmax = MinMaxScaler()
m_result = minmax.fit_transform(x)
df_minmax = pd.DataFrame(m_result,columns=x.columns)

df_minmax.head()

,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit,Year
0,0.94,0.928571,0.75,0.857143,0.857143,0.905660,1.0,0.923077,0.0
1,0.68,0.535714,0.75,0.738095,0.857143,0.660377,1.0,0.676923,0.0
2,0.52,0.428571,0.50,0.500000,0.619048,0.386792,1.0,0.615385,0.0
3,0.64,0.642857,0.50,0.619048,0.380952,0.597484,1.0,0.738462,0.0
4,0.48,0.392857,0.25,0.261905,0.500000,0.452830,0.0,0.507692,0.0

In [22]:
# robust scaler 
robust = RobustScaler()

r_result = robust.fit_transform(x)
robust_df = pd.DataFrame(r_result,columns=x.columns)
print(robust_df.head())

   GRE Score  TOEFL Score  University Rating       SOP  LOR      CGPA  \
0   0.988235     0.916667                0.5  0.666667  1.0  1.202247
1   0.376471     0.000000                0.5  0.333333  1.0  0.325843
2   0.000000    -0.250000                0.0 -0.333333  0.0 -0.651685
3   0.282353     0.250000                0.0  0.000000 -1.0  0.101124
4  -0.094118    -0.333333               -0.5 -1.000000 -0.5 -0.415730

   Research  Chance of Admit  Year
0       0.0         1.095890  -1.0
1       0.0         0.219178  -1.0
2       0.0         0.000000  -1.0
3       0.0         0.438356  -1.0
4      -1.0        -0.383562  -1.0

In [24]:
standard = StandardScaler()

result_s = standard.fit_transform(x)
standard_df = pd.DataFrame(result_s,columns=x.columns)
print(standard_df.head())

   GRE Score  TOEFL Score  University Rating       SOP       LOR      CGPA  \
0   1.568729     1.498730           0.747850  1.077656  1.226474  1.732756
1   0.599227     0.057139           0.747850  0.590690  1.226474  0.457962
2   0.002610    -0.336022          -0.011389 -0.383242  0.104665 -0.963924
3   0.450073     0.450301          -0.011389  0.103724 -1.017144  0.131091
4  -0.146544    -0.467075          -0.770627 -1.357174 -0.456240 -0.620710

   Research  Chance of Admit      Year
0  0.994018         1.386682 -1.414214
1  0.994018         0.289569 -1.414214
2  0.994018         0.015291 -1.414214
3  0.994018         0.563847 -1.414214
4 -1.006018        -0.464696 -1.414214